# This will start a haproxy and 4 web services. haproxy will act as a loadbalancer.
# Authors: yeasy.github.com
# Date: 2015-11-15

version: "3.9"
services:
    web1:
        build: ./web
        expose:
            - 80
        command: python index.py server1 0
    web2:
        build: ./web
        expose:
            - 80
        command: python index.py server2 0
    web3:
        build: ./web 
        expose:
            - 80
        command: python index.py server3 0
    web4:
        build: ./web 
        expose:
            - 80
        command: python index.py server4 0
    haproxy:
        image: haproxy:2.7
        volumes:
            - ./haproxy:/haproxy-override
            - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
        links:
            - web1
            - web2
            - web3
            - web4
        ports:
            - "80:80"
            - "70:70" # haproxy admin console, login with user:pass